name: dynibar
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3
  - pip:
    - torch==1.10.1
    - torchvision==0.11.3
    - configargparse
    - scikit-image==0.19.3
    - matplotlib
    - opencv-python
    - torch_efficient_distloss
    - imageio==2.22.0
    - pillow==8.3.2
    - tensorboard==2.10.0
    - scipy==1.9.1
    - timm==0.6.7
    - kornia==0.6.7
    - ninja==1.11.1
    - setuptools==59.5.0
